spring:
  datasource:
    url:  jdbc:mysql://173.255.204.137/digitaldiary?serverTimezone=UTC
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: mydbuser
    password: Datauser@123


server:
  servlet:
    context-path: /mydiary


